import type { Metadata } from "next";
import { Almarai } from "next/font/google";
import "../globals.css";
import { LazyMotion, domAnimation } from "motion/react";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import Navbar from "@/components/base/Navbar";
import Footer from "@/components/base/Footer";

const almarai = Almarai({
  weight: ["300", "400", "700"],
  display: "swap",
  fallback: ["system-ui", "sans-serif"],
  style: "normal",
  subsets: ["arabic"],
  variable: "--font-almarai",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  robots: {
    notranslate: true,
  },
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const locale = (await params).locale;

  if (!routing.locales.includes(locale as "en" | "ar")) {
    notFound();
  }

  const message = await getMessages();

  return (
    <html
      dir={locale === "ar" ? "rtl" : "ltr"}
      lang={locale}
      suppressHydrationWarning
    >
      <body className={`${almarai.className} antialiased`}>
        <NextIntlClientProvider messages={message}>
          <LazyMotion features={domAnimation}>
            <Navbar />
            {children}
            <Footer />
          </LazyMotion>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
